apiVersion: apps/v1
kind: Deployment

metadata:
  name: angular-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: angular

  template:
    metadata:
      labels:
        app: angular

    spec:
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"

      - key: "karpenter.sh/disrupted"
        operator: "Exists"
        effect: "NoSchedule"

      containers:
      - name: angular-app
        image: 592934232382.dkr.ecr.eu-north-1.amazonaws.com/my-angular-app:latest
        ports:
        - containerPort: 80