import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Authservice } from '../authservice';
import { DropDownsModule } from '@progress/kendo-angular-dropdowns';

interface User {
  user_id: number;
  username: string;
}

@Component({
  selector: 'app-givemoney',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, DropDownsModule],
  templateUrl: './givemoney.html',
  styleUrl: './givemoney.css'
})
export class Givemoney implements OnInit {
  giveMoneyForm: FormGroup;
  isLoading: boolean = false;
  transactionId: number | null = null;
  errorMessage: string | null = null;
  successMessage: string | null = null;
  isAutoGenerated: boolean = true;
  isCharterFocused: boolean = false;
  
  // Users list for dropdown
  usersList: User[] = [];
  filteredUsers: User[] = [];
  selectedCustomer: User | null = null;
  isUsersLoading: boolean = false;

  constructor(
    private fb: FormBuilder,
    private accountService: Authservice
  ) {
    // Initialize Give Money Form
    this.giveMoneyForm = this.fb.group({
      giveCustomerName: ['', [Validators.required]],
      giveUtiNo: [''],
      givemoney: ['', [Validators.required, Validators.min(0)]],
      giveCharterDescription: [''], // Auto-generated from amount
      giveDate: [this.getCurrentDate()],
      giveAgent: [''],
      giveRemark: ['']
    });

    // Auto-generate charter description when amount changes
    this.giveMoneyForm.get('givemoney')?.valueChanges.subscribe(() => {
      this.onAmountChange();
    });
  }

  ngOnInit() {
    this.loadUsers();
  }

  // Load users for dropdown
  loadUsers() {
    this.isUsersLoading = true;
    this.accountService.getUsersBasicInfo().subscribe({
      next: (response: any) => {
        this.isUsersLoading = false;
        if (response.success && response.data) {
          this.usersList = response.data;
          this.filteredUsers = [...this.usersList];
          console.log('Loaded users:', this.usersList);
        } else {
          this.errorMessage = 'Failed to load customers list.';
        }
      },
      error: (error: any) => {
        this.isUsersLoading = false;
        console.error('Error loading users:', error);
        this.errorMessage = 'Error loading customers list. Please try again.';
      }
    });
  }

  // Handle customer selection change
  onCustomerChange(userId: number) {
    this.selectedCustomer = this.usersList.find(user => user.user_id === userId) || null;
    console.log('Selected customer:', this.selectedCustomer);
    
    // Auto-generate charter description if amount exists
    if (this.selectedCustomer && this.giveMoneyForm.get('givemoney')?.value) {
      this.generateCharterDescription();
    }
  }

  // Handle amount change and auto-generate charter description
  onAmountChange() {
    if (this.isAutoGenerated && !this.isCharterFocused) {
      this.generateCharterDescription();
    }
  }

  // Generate charter description automatically from amount
  generateCharterDescription() {
    const amount = parseFloat(this.giveMoneyForm.get('givemoney')?.value);
    if (amount && amount > 0) {
      const amountInWords = this.convertAmountToWords(amount);
      const customerName = this.selectedCustomer?.username || 'Customer';
      const charterText = `${amountInWords} Only for ${customerName}`;
      
      this.giveMoneyForm.patchValue({
        giveCharterDescription: charterText
      }, { emitEvent: false });
    } else {
      this.giveMoneyForm.patchValue({
        giveCharterDescription: ''
      }, { emitEvent: false });
    }
  }

  // Convert numeric amount to words
  convertAmountToWords(amount: number): string {
    const units = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine'];
    const teens = ['Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
    const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
    
    function convertLessThanThousand(num: number): string {
      if (num === 0) return '';
      
      let words = '';
      let tempNum = num;
      
      // Hundreds
      if (tempNum >= 100) {
        words += units[Math.floor(tempNum / 100)] + ' Hundred ';
        tempNum %= 100;
      }
      
      // Tens and Units
      if (tempNum >= 20) {
        words += tens[Math.floor(tempNum / 10)] + ' ';
        tempNum %= 10;
      } else if (tempNum >= 10) {
        words += teens[tempNum - 10] + ' ';
        tempNum = 0;
      }
      
      // Units
      if (tempNum > 0) {
        words += units[tempNum] + ' ';
      }
      
      return words.trim();
    }
    
    if (amount === 0) return 'Zero';
    
    let result = '';
    let rupees = Math.floor(amount);
    const paise = Math.round((amount - rupees) * 100);
    
    // Convert rupees - Crores
    if (rupees >= 10000000) {
      result += convertLessThanThousand(Math.floor(rupees / 10000000)) + ' Crore ';
      rupees %= 10000000;
    }
    
    // Lakhs
    if (rupees >= 100000) {
      result += convertLessThanThousand(Math.floor(rupees / 100000)) + ' Lakh ';
      rupees %= 100000;
    }
    
    // Thousands
    if (rupees >= 1000) {
      result += convertLessThanThousand(Math.floor(rupees / 1000)) + ' Thousand ';
      rupees %= 1000;
    }
    
    // Hundreds and below
    if (rupees > 0) {
      result += convertLessThanThousand(rupees);
    }
    
    result = result.trim() + ' Rupees';
    
    // Convert paise
    if (paise > 0) {
      result += ' and ' + convertLessThanThousand(paise) + ' Paise';
    }
    
    return result;
  }

  // Enable manual editing of charter description when clicked
  enableCharterEdit() {
    if (this.isAutoGenerated) {
      this.isAutoGenerated = false;
    }
    this.isCharterFocused = true;
  }

  // Handle charter input focus
  onCharterFocus() {
    this.isCharterFocused = true;
  }

  // Handle charter input blur (when focus is lost)
  onCharterBlur() {
    this.isCharterFocused = false;
    
    // If charter is empty after manual editing, switch back to auto-generate mode
    if (!this.giveMoneyForm.get('giveCharterDescription')?.value) {
      this.isAutoGenerated = true;
      this.generateCharterDescription();
    }
  }

  // Handle filter change for dropdown
  onFilter(filter: any) {
    if (filter && filter.length > 0) {
      const filterText = filter.toLowerCase();
      this.filteredUsers = this.usersList.filter(user => 
        user.username.toLowerCase().includes(filterText) ||
        user.user_id.toString().includes(filter)
      );
    } else {
      this.filteredUsers = [...this.usersList];
    }
  }

  getCurrentDate(): string {
    return new Date().toISOString().split('T')[0];
  }

  // Clear messages
  clearMessages() {
    this.errorMessage = null;
    this.successMessage = null;
  }

  // Submit Give Money Only
  onSubmit() {
    this.clearMessages();
    
    if (this.giveMoneyForm.valid && this.selectedCustomer) {
      this.isLoading = true;
      
      const giveMoneyData = this.giveMoneyForm.value;
      
      // Map form data for Give Money only
      const accountData = {
        givename: this.selectedCustomer.user_id.toString(), // Pass user_id as name
        givemoney: giveMoneyData.givemoney,
        giveCharterDescription: giveMoneyData.giveCharterDescription || undefined, // Include charter description
        givedate: giveMoneyData.giveDate ? new Date(giveMoneyData.giveDate) : undefined,
        giveagent: giveMoneyData.giveAgent || undefined,
        giveremark: giveMoneyData.giveRemark || undefined,
        giveutino: giveMoneyData.giveUtiNo ? parseFloat(giveMoneyData.giveUtiNo) : undefined
      };

      console.log('Submitting Give Money Data:', accountData);

      // Call service to create Give Money transaction
      this.accountService.createGiveMoneyTransaction(accountData).subscribe({
        next: (response: any) => {
          this.isLoading = false;
          console.log('Give Money API Response:', response);
          
          if (response && response.success) {
            const accountId = response.acid;
            this.transactionId = accountId;
            
            // Show success message
            let successMsg = `Give Money transaction created successfully for ${this.selectedCustomer?.username}! Transaction ID: ${accountId}`;
            
            // Add charter description info if provided
            if (giveMoneyData.giveCharterDescription) {
              successMsg += ` | Charter: "${giveMoneyData.giveCharterDescription}"`;
            }
            
            this.successMessage = successMsg;
            
            this.resetForm();
          } else {
            // Show error message from backend
            this.errorMessage = response?.message || 'Failed to create Give Money transaction. Please try again.';
          }
        },
        error: (error: any) => {
          this.isLoading = false;
          console.error('Error creating Give Money transaction:', error);
          
          // Use the backend error message directly
          if (error.error && error.error.message) {
            this.errorMessage = error.error.message;
          } else if (error.status === 400) {
            this.errorMessage = 'Bad request. Please check your input data.';
          } else if (error.status === 500) {
            this.errorMessage = 'Server error. Please try again later.';
          } else {
            this.errorMessage = 'Error creating Give Money transaction. Please try again.';
          }
        }
      });
    } else {
      this.errorMessage = 'Please fill all required fields correctly and select a customer.';
      Object.keys(this.giveMoneyForm.controls).forEach(key => {
        this.giveMoneyForm.get(key)?.markAsTouched();
      });
    }
  }

  resetForm() {
    this.giveMoneyForm.reset({
      giveDate: this.getCurrentDate()
    });
    this.transactionId = null;
    this.selectedCustomer = null;
    this.isAutoGenerated = true;
    this.isCharterFocused = false;
    this.clearMessages();
  }
}