import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Authservice } from '../authservice';
import { DropDownsModule } from '@progress/kendo-angular-dropdowns';

interface User {
  user_id: number;
  username: string;
}

@Component({
  selector: 'app-insert-account',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, DropDownsModule],
  templateUrl: './insert-account.html',
  styleUrl: './insert-account.css'
})
export class InsertAccount implements OnInit {
  getMoneyForm: FormGroup;
  netAmount: number = 0;
  isLoading: boolean = false;
  transactionId: number | null = null;
  errorMessage: string | null = null;
  successMessage: string | null = null;
  apiResponse: any = null;
  isAutoGenerated: boolean = true;
  isCharterFocused: boolean = false;
  
  // Users list for dropdown
  usersList: User[] = [];
  filteredUsers: User[] = [];
  selectedCustomer: User | null = null;
  isUsersLoading: boolean = false;

  constructor(
    private fb: FormBuilder,
    private accountService: Authservice
  ) {
    // Initialize Get Money Form
    this.getMoneyForm = this.fb.group({
      name: ['', [Validators.required]],
      getmoney: ['', [Validators.required, Validators.min(0)]],
      charterDescription: [''], // Auto-generated from amount
      intrest: ['', [Validators.required, Validators.min(0), Validators.max(100)]],
      utiNo: [''],
      getAgent: [''],
      getDate: [this.getCurrentDate()],
      getRemark: ['']
    });

    // Calculate net amount when getmoney or intrest changes
    this.getMoneyForm.get('getmoney')?.valueChanges.subscribe(() => {
      this.calculateNetAmount();
      this.onAmountChange();
    });
    this.getMoneyForm.get('intrest')?.valueChanges.subscribe(() => this.calculateNetAmount());
  }

  ngOnInit() {
    this.loadUsers();
  }

  // Load users for dropdown
  loadUsers() {
    this.isUsersLoading = true;
    this.accountService.getUsersBasicInfo().subscribe({
      next: (response: any) => {
        this.isUsersLoading = false;
        if (response.success && response.data) {
          this.usersList = response.data;
          this.filteredUsers = [...this.usersList];
          console.log('Loaded users:', this.usersList);
        } else {
          this.errorMessage = 'Failed to load customers list.';
        }
      },
      error: (error: any) => {
        this.isUsersLoading = false;
        console.error('Error loading users:', error);
        this.errorMessage = 'Error loading customers list. Please try again.';
      }
    });
  }

  // Handle customer selection change
  onCustomerChange(userId: number) {
    this.selectedCustomer = this.usersList.find(user => user.user_id === userId) || null;
    console.log('Selected customer:', this.selectedCustomer);
    
    // Auto-generate charter description if amount exists
    if (this.selectedCustomer && this.getMoneyForm.get('getmoney')?.value) {
      this.generateCharterDescription();
    }
  }

  // Handle amount change and auto-generate charter description
  onAmountChange() {
    if (this.isAutoGenerated && !this.isCharterFocused) {
      this.generateCharterDescription();
    }
  }

  // Generate charter description automatically from amount
  generateCharterDescription() {
    const amount = parseFloat(this.getMoneyForm.get('getmoney')?.value);
    if (amount && amount > 0) {
      const amountInWords = this.convertAmountToWords(amount);
      const customerName = this.selectedCustomer?.username || 'Customer';
      const charterText = `${amountInWords} Only for ${customerName}`;
      
      this.getMoneyForm.patchValue({
        charterDescription: charterText
      }, { emitEvent: false });
    } else {
      this.getMoneyForm.patchValue({
        charterDescription: ''
      }, { emitEvent: false });
    }
  }

  // Convert numeric amount to words
  convertAmountToWords(amount: number): string {
    const units = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine'];
    const teens = ['Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
    const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
    
    function convertLessThanThousand(num: number): string {
      if (num === 0) return '';
      
      let words = '';
      let tempNum = num;
      
      // Hundreds
      if (tempNum >= 100) {
        words += units[Math.floor(tempNum / 100)] + ' Hundred ';
        tempNum %= 100;
      }
      
      // Tens and Units
      if (tempNum >= 20) {
        words += tens[Math.floor(tempNum / 10)] + ' ';
        tempNum %= 10;
      } else if (tempNum >= 10) {
        words += teens[tempNum - 10] + ' ';
        tempNum = 0;
      }
      
      // Units
      if (tempNum > 0) {
        words += units[tempNum] + ' ';
      }
      
      return words.trim();
    }
    
    if (amount === 0) return 'Zero';
    
    let result = '';
    let rupees = Math.floor(amount);
    const paise = Math.round((amount - rupees) * 100);
    
    // Convert rupees - Crores
    if (rupees >= 10000000) {
      result += convertLessThanThousand(Math.floor(rupees / 10000000)) + ' Crore ';
      rupees %= 10000000;
    }
    
    // Lakhs
    if (rupees >= 100000) {
      result += convertLessThanThousand(Math.floor(rupees / 100000)) + ' Lakh ';
      rupees %= 100000;
    }
    
    // Thousands
    if (rupees >= 1000) {
      result += convertLessThanThousand(Math.floor(rupees / 1000)) + ' Thousand ';
      rupees %= 1000;
    }
    
    // Hundreds and below
    if (rupees > 0) {
      result += convertLessThanThousand(rupees);
    }
    
    result = result.trim() + ' Rupees';
    
    // Convert paise
    if (paise > 0) {
      result += ' and ' + convertLessThanThousand(paise) + ' Paise';
    }
    
    return result;
  }

  // Enable manual editing of charter description when clicked
  enableCharterEdit() {
    if (this.isAutoGenerated) {
      this.isAutoGenerated = false;
    }
    this.isCharterFocused = true;
  }

  // Handle charter input focus
  onCharterFocus() {
    this.isCharterFocused = true;
  }

  // Handle charter input blur (when focus is lost)
  onCharterBlur() {
    this.isCharterFocused = false;
    
    // If charter is empty after manual editing, switch back to auto-generate mode
    if (!this.getMoneyForm.get('charterDescription')?.value) {
      this.isAutoGenerated = true;
      this.generateCharterDescription();
    }
  }

  // Handle filter change for dropdown
  onFilter(filter: any) {
    if (filter && filter.length > 0) {
      const filterText = filter.toLowerCase();
      this.filteredUsers = this.usersList.filter(user => 
        user.username.toLowerCase().includes(filterText) ||
        user.user_id.toString().includes(filter)
      );
    } else {
      this.filteredUsers = [...this.usersList];
    }
  }

  getCurrentDate(): string {
    return new Date().toISOString().split('T')[0];
  }

  calculateNetAmount() {
    const getmoney = parseFloat(this.getMoneyForm.get('getmoney')?.value) || 0;
    const intrest = parseFloat(this.getMoneyForm.get('intrest')?.value) || 0;
    
    if (getmoney > 0 && intrest > 0) {
      this.netAmount = getmoney - (getmoney * intrest / 100);
    } else {
      this.netAmount = getmoney;
    }
  }

  // Clear messages and response
  clearMessages() {
    this.errorMessage = null;
    this.successMessage = null;
    this.apiResponse = null;
  }

  // Submit Get Money Only
  onSubmit() {
    this.clearMessages();
    
    if (this.getMoneyForm.valid && this.selectedCustomer) {
      this.isLoading = true;
      
      const getMoneyData = this.getMoneyForm.value;
      
      // Map form data to Account model for Get Money only
      const accountData = {
        name: this.selectedCustomer.user_id.toString(),
        getmoney: getMoneyData.getmoney,
        charterDescription: getMoneyData.charterDescription || undefined,
        intrest: getMoneyData.intrest,
        date: getMoneyData.getDate ? new Date(getMoneyData.getDate) : undefined,
        agent: getMoneyData.getAgent || undefined,
        remark: getMoneyData.getRemark || undefined,
        utino: getMoneyData.utiNo ? parseFloat(getMoneyData.utiNo) : undefined
      };

      console.log('Submitting Get Money Data:', accountData);

      // Call service to create Get Money transaction
      this.accountService.createGetMoneyTransaction(accountData).subscribe({
        next: (response: any) => {
          this.isLoading = false;
          console.log('Complete API Response:', response);
          
          this.apiResponse = response;
          
          if (response && response.success) {
            const accountId = response.acid;
            this.transactionId = accountId;
            
            let successMsg = `Get Money transaction created successfully for ${this.selectedCustomer?.username}! Transaction ID: ${accountId}`;
            
            if (getMoneyData.charterDescription) {
              successMsg += ` | Charter: "${getMoneyData.charterDescription}"`;
            }
            
            this.successMessage = successMsg;
            
            this.resetForm();
          } else {
            this.errorMessage = response?.message || 'Failed to create Get Money transaction.';
          }
        },
        error: (error: any) => {
          this.isLoading = false;
          console.error('Complete Error Response:', error);
          
          this.apiResponse = error.error || error;
          
          if (error.error && error.error.message) {
            this.errorMessage = error.error.message;
          } else if (error.status === 400) {
            this.errorMessage = 'Bad request. Please check your input data.';
          } else if (error.status === 500) {
            this.errorMessage = 'Server error. Please try again later.';
          } else {
            this.errorMessage = 'Error creating Get Money transaction. Please try again.';
          }
        }
      });
    } else {
      this.errorMessage = 'Please fill all required fields correctly and select a customer.';
      Object.keys(this.getMoneyForm.controls).forEach(key => {
        this.getMoneyForm.get(key)?.markAsTouched();
      });
    }
  }

  resetForm() {
    this.getMoneyForm.reset({
      getDate: this.getCurrentDate()
    });
    this.netAmount = 0;
    this.transactionId = null;
    this.selectedCustomer = null;
    this.isAutoGenerated = true;
    this.isCharterFocused = false;
    this.clearMessages();
  }
}